# Generated by Django 5.0.1 on 2024-01-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0007_brands_owners'),
        ('users', '0002_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_sneakers',
            field=models.ManyToManyField(blank=True, to='sneakers.sneakers', verbose_name='Tênis Favoritos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_active',
            field=models.BooleanField(default=False, verbose_name='Notificações Ativas'),
        ),
    ]
