# Generated by Django 5.0.1 on 2024-01-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_user',
            field=models.CharField(choices=[('client', 'Cliente'), ('employee', 'Funcionário'), ('admin', 'Admin')], verbose_name='Tipo do Usuário'),
        ),
    ]
