# Generated by Django 5.0.1 on 2024-02-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', help_text='Insira o telefone com o DDD na frente ex:(00) 90000-0000', verbose_name='Telefone'),
        ),
    ]
