# Generated by Django 5.0.1 on 2024-02-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Insira o telefone com o DDD na frente ex:(00) 90000-0000', null=True, verbose_name='Telefone'),
        ),
    ]
