# Generated by Django 5.0.1 on 2024-03-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cep',
            field=models.CharField(default=0, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default=1, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='complement',
            field=models.CharField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_house',
            field=models.CharField(default=1, verbose_name='Número da casa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default=1, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(default=1, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
