# Generated by Django 5.0.1 on 2024-03-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0017_remove_lines_create_line_lines_name_line'),
        ('users', '0011_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='user_shopping_cart', to='sneakers.sneakers', verbose_name='Carrinho de compras'),
        ),
    ]
