# Generated by Django 5.0.1 on 2024-01-18 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sneakers', '0011_alter_adverts_create_at'),
        ('type_payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Nome da Loja')),
                ('street', models.CharField(verbose_name='Rua')),
                ('number', models.CharField(verbose_name='Número')),
                ('state', models.CharField(verbose_name='Estado')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('owner', models.ManyToManyField(related_name='onwers_store', to=settings.AUTH_USER_MODEL, verbose_name='Dono(s)')),
                ('products', models.ManyToManyField(related_name='sneakers_store', to='sneakers.sneakers', verbose_name='Tênis Disponiveis')),
                ('type_payments', models.ManyToManyField(related_name='type_payments_store', to='type_payments.typepayments', verbose_name='Tipos de Pagamentos Aceitáveis')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
    ]
