# Generated by Django 5.0.1 on 2024-01-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_delivery_store_maximum_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default='21:00', verbose_name='Horário de fechamento'),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default='08:00', verbose_name='Horário de abertura'),
        ),
    ]
