# Generated by Django 5.0.1 on 2024-02-19 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_closing_time_store_opening_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(default=1, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='employees',
            field=models.ManyToManyField(related_name='store_employee', to=settings.AUTH_USER_MODEL, verbose_name='Funcionários'),
        ),
    ]
