# Generated by Django 5.0.1 on 2024-03-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0017_remove_lines_create_line_lines_name_line'),
        ('store', '0005_store_city_store_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='orders',
            field=models.ManyToManyField(null=True, to='sneakers.sneakers', verbose_name='Pedidos'),
        ),
    ]
