# Generated by Django 5.0.1 on 2024-01-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Foto')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('brand', models.CharField(choices=[('adidas', 'Adidas'), ('nike', 'Nike'), ('puma', 'Puma'), ('umbro', 'Umbro'), ('under_armour', 'Under Armour')], default='', max_length=100, verbose_name='Marca')),
                ('line', models.CharField(max_length=255, verbose_name='Linha')),
                ('model', models.CharField(max_length=55, verbose_name='Modelo')),
            ],
        ),
    ]
