# Generated by Django 5.0.1 on 2024-01-06 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=120, verbose_name='Nome da Marca')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sneakers',
            options={'verbose_name': 'Tênis', 'verbose_name_plural': 'Tênis'},
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sneakers.brands', verbose_name='Marca'),
        ),
    ]
