# Generated by Django 5.0.1 on 2024-01-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_brands_alter_sneakers_options_alter_sneakers_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_line', models.CharField(max_length=50, verbose_name='Criar Linha')),
            ],
            options={
                'verbose_name': 'Linha de Tênis',
                'verbose_name_plural': 'Linhas de Tênis',
            },
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sneakers.lines', verbose_name='Pertence a linha'),
        ),
    ]
