# Generated by Django 5.0.1 on 2024-01-06 18:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0003_lines_alter_sneakers_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='available_sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=4), default=list, size=None, verbose_name='Tamanhos Disponiveis'),
        ),
    ]
