# Generated by Django 5.0.1 on 2024-01-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0004_sneakers_available_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
