# Generated by Django 5.0.1 on 2024-01-07 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0005_alter_brands_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lines',
            name='brand_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_line', to='sneakers.brands', verbose_name='Linha da Marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sneaker_brand', to='sneakers.brands', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sneaker_line', to='sneakers.lines', verbose_name='Pertence a linha'),
        ),
    ]
