# Generated by Django 5.0.1 on 2024-01-07 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0006_lines_brand_line_alter_sneakers_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='owners',
            field=models.ManyToManyField(related_name='users_owners', to=settings.AUTH_USER_MODEL, verbose_name='Donos/Sócios'),
        ),
    ]
