# Generated by Django 5.0.1 on 2024-01-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0007_brands_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='Em Estoque'),
        ),
    ]
