# Generated by Django 5.0.1 on 2024-01-14 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0008_sneakers_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adverts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ImageField(upload_to='', verbose_name='Anúncio')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expiration', models.DateTimeField(verbose_name='Expira em')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneaker_advert', to='sneakers.sneakers', verbose_name='Tênis presente no anúncio')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
            },
        ),
    ]
