# Generated by Django 5.0.1 on 2024-01-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0010_alter_adverts_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='create_at',
            field=models.DateTimeField(help_text='OBS: A DATA DE CRIAÇÃO SERVE PARA INDICAR A PARTIR DE QUAL DATA O ANÙNCIO ESTARÁ VALENDO', verbose_name='Criado em'),
        ),
    ]
