# Generated by Django 5.0.1 on 2024-01-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0011_alter_adverts_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Anúncio'),
        ),
    ]
