# Generated by Django 5.0.1 on 2024-01-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0013_alter_adverts_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverts',
            name='sneaker',
        ),
        migrations.AddField(
            model_name='adverts',
            name='sneaker',
            field=models.ManyToManyField(related_name='sneaker_advert', to='sneakers.sneakers', verbose_name='Tênis presente no anúncio'),
        ),
    ]
