# Generated by Django 5.0.1 on 2024-01-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0014_remove_adverts_sneaker_adverts_sneaker'),
        ('store', '0003_store_delivery_store_maximum_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='stores',
            field=models.ManyToManyField(related_name='stores_sneakers', to='store.store', verbose_name='Lojas disponiveis'),
        ),
    ]
