# Generated by Django 5.0.1 on 2024-02-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0016_remove_sneakers_stores_sneakers_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lines',
            name='create_line',
        ),
        migrations.AddField(
            model_name='lines',
            name='name_line',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome da Linha'),
            preserve_default=False,
        ),
    ]
