# Generated by Django 5.0.1 on 2024-02-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(verbose_name='Compania')),
                ('phone', models.CharField(verbose_name='Telefone')),
                ('description', models.TextField(max_length=300, verbose_name='Sobre nós')),
            ],
            options={
                'verbose_name': 'Sobre nós',
                'verbose_name_plural': 'Sobre nós',
            },
        ),
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.FileField(upload_to='terms_of_use/')),
            ],
            options={
                'verbose_name': 'Termo de Uso',
                'verbose_name_plural': 'Termos de Uso',
            },
        ),
    ]
