# Generated by Django 5.0.1 on 2024-02-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.FileField(upload_to='privacy_police/')),
            ],
            options={
                'verbose_name': 'Politica de Privacidade',
                'verbose_name_plural': 'Politicas de Privacidade',
            },
        ),
    ]
