# Generated by Django 5.0.1 on 2024-03-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_alter_privacypolicy_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='Whatsapp'),
        ),
    ]
