# Generated by Django 5.0.1 on 2024-01-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchases_type_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='sneaker_size',
            field=models.FloatField(default=0.0, max_length=4, verbose_name='Tamanho'),
        ),
    ]
