# Generated by Django 5.0.1 on 2024-02-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchases_sneaker_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='employee_discount',
            field=models.BooleanField(default=False, verbose_name='Desconto para funcionário'),
        ),
    ]
