# Generated by Django 5.0.1 on 2024-02-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notifications_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de envio'),
        ),
    ]
