# Generated by Django 5.0.1 on 2024-03-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notifications_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='purchase_notification',
            field=models.BooleanField(default=False, verbose_name='Notificação de compra'),
        ),
    ]
